branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  -

  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"

  - - "@semantic-release/changelog"
    - changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file. See [Conventional Commits](https://conventionalcommits.org) for commit guidelines."

  - - "semantic-release/exec"
    - prepareCmd: "echo ${nextRelease.version} > VERSION"

  - - "semantic-release/exec"
    - prepareCmd: |
        cd packages/parsec && clojure -T:build uber
        cd ../..
        cd packages/parsec-api && clojure -T:build uber

  # - - "@semantic-release/git"
  #   - message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # - - "@semantic-release/github"
