name: Test

on:
  pull_request:

jobs:
  parsec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/parsec
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.10.3.1087
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        run: clojure -X:test

  parsec-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/parsec-api
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.10.3.1087
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        run: clojure -X:test
